[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=--ld-path=/home/kwach/.cargo/bin/wild"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
